// ============================================================
//  WEB MODE — BAKING A TEMPLATE INTO CSS @keyframes
//  The preview poses elements every frame from JS. The export can't ship that
//  loop, so the same pure transform is sampled across one clip and written out
//  as keyframes. This is only sound because of loopCycles() (lib/motion.ts):
//  it guarantees frame totalFrames ≡ frame 0, so 0% and 100% agree and the
//  loop is seamless without a stitch.
// ============================================================

import type { Template, TransformCtx } from './types';
import type { LayoutMode, Size } from '@/store/useWebStore';
import { clipPathCss, poseFor, transformCss } from './webPose';

export const STAGE_CLASS = 'msx-stage';

export interface BakeOpts {
  template: Template;
  mode: LayoutMode;
  values: Record<string, any>;
  selectors: string[];        // structural paths, relative to the stage root
  canvas: Size;
  duration: number;           // seconds
  fps: number;
  ease: (t: number) => number;
  /** Keyframe stops per layer. More = closer to the preview, bigger CSS. */
  samples?: number;
}

const num = (n: number) => (Math.round(n * 1000) / 1000).toString();

export function bakeCss(o: BakeOpts): string {
  const totalFrames = Math.max(1, Math.round(o.duration * o.fps));
  // Cap the stops: at 30fps an 8s clip is 240 frames per layer, and CSS
  // interpolates linearly between stops anyway. ~120 is past the point where
  // more stops are visible, and keeps the file readable.
  const samples = Math.min(o.samples ?? 120, totalFrames);
  const count = o.selectors.length;

  const ctx: TransformCtx = {
    fps: o.fps,
    width: o.canvas.w,
    height: o.canvas.h,
    duration: o.duration,
    totalFrames,
    ease: o.ease,
    easedPhase: (p: number) => { const b = Math.floor(p); return b + o.ease(p - b); },
  };

  const out: string[] = [];
  out.push(`/* Generated by Motion Studio — template: ${o.template.meta.name} (${o.template.meta.id}) */`);
  out.push(`/* Layout mode: ${o.mode} · canvas ${o.canvas.w}×${o.canvas.h} · ${o.duration}s @ ${o.fps}fps */`);
  out.push('');

  // ---- stage ----
  if (o.mode === 'own') {
    out.push(`.${STAGE_CLASS} {`);
    out.push(`  position: relative;`);
    out.push(`  width: ${o.canvas.w}px;`);
    out.push(`  height: ${o.canvas.h}px;`);
    out.push(`  overflow: hidden;`);
    out.push(`}`);
  } else {
    out.push(`.${STAGE_CLASS} { position: relative; }`);
  }
  out.push('');

  // ---- per-layer keyframes ----
  for (let i = 0; i < count; i++) {
    const name = `msx-layer-${i}`;
    const steps: string[] = [];
    for (let s = 0; s <= samples; s++) {
      const pct = (s / samples) * 100;
      const frame = (s / samples) * totalFrames;
      const t = poseFor(o.template, o.mode, frame, i, count, { ...o.values, count }, ctx);
      const dim = Math.max(0, Math.min(1, t.dim ?? 0));
      const decls = [
        `transform: ${transformCss(t, o.mode)}`,
        `opacity: ${num(t.alpha)}`,
        // A receding card darkens instead of going see-through — same rule as
        // the sprite renderer, so exported CSS matches the stage.
        `filter: brightness(${num(1 - dim)})`,
        `clip-path: ${clipPathCss(t) || 'inset(0)'}`,
        `z-index: ${Math.round(t.depth * 1000 + i)}`,
      ];
      steps.push(`  ${num(pct)}% { ${decls.join('; ')}; }`);
    }
    out.push(`@keyframes ${name} {`);
    out.push(steps.join('\n'));
    out.push(`}`);
    out.push('');
  }

  // ---- per-layer rules ----
  for (let i = 0; i < count; i++) {
    const sel = `.${STAGE_CLASS} > ${o.selectors[i]}`;
    out.push(`${sel} {`);
    if (o.mode === 'own') {
      out.push(`  position: absolute;`);
      out.push(`  left: 50%;`);
      out.push(`  top: 50%;`);
      out.push(`  margin: 0;`);
    }
    // linear, always: the scene's easing curve is already baked into where the
    // samples fall. A timing function here would apply it a second time.
    out.push(`  animation: msx-layer-${i} ${num(o.duration)}s linear infinite;`);
    out.push(`  animation-play-state: var(--msx-play, running);`);
    out.push(`}`);
    out.push('');
  }

  // Descendant, not child: the animated elements sit wherever the selectors
  // pointed, which is rarely the stage's own children.
  out.push(`@media (prefers-reduced-motion: reduce) {`);
  out.push(`  .${STAGE_CLASS} * { animation: none !important; }`);
  out.push(`}`);
  out.push('');
  return out.join('\n');
}
